CREATE TABLE `actualite` (
  `ID_ACTU` int(2) NOT NULL,
  `TITRE` varchar(255) DEFAULT NULL,
  `MESSAGE` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `appeler` (
  `ID_APPEL` int(2) NOT NULL,
  `ID_USER` int(2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `appel_video` (
  `ID_APPEL` int(2) NOT NULL,
  `DATE_APPEL` timestamp NULL DEFAULT NULL,
  `DUREE` int(2) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `creer` (
  `ID_USER` int(2) NOT NULL,
  `ID_REUNION` int(2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `envoyer` (
  `ID_USER` int(2) NOT NULL,
  `ID_MESSAGE` int(2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `etre_appele` (
  `ID_USER` int(2) NOT NULL,
  `ID_APPEL` int(2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `message` (
  `ID_MESSAGE` int(2) NOT NULL,
  `CONTENU` text DEFAULT NULL,
  `DATE_MESSAGE` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `recevoir` (
  `ID_MESSAGE` int(2) NOT NULL,
  `ID_USER` int(2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `reunion` (
  `ID_REUNION` int(2) NOT NULL,
  `NOM` varchar(255) DEFAULT NULL,
  `DESCRIPTION` text DEFAULT NULL,
  `DATE_REUNION` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `utilisateur` (
  `ID_USER` int(2) NOT NULL,
  `PSEUDO` varchar(255) DEFAULT NULL,
  `NOM` varchar(255) DEFAULT NULL,
  `PRENOM` varchar(255) DEFAULT NULL,
  `PASSWORD` varchar(255) DEFAULT NULL,
  `SOCIETE` varchar(255) DEFAULT NULL,
  `BIO` text DEFAULT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  `TELEPHONE` varchar(255) DEFAULT NULL,
  `IMG` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


ALTER TABLE `actualite`
  ADD PRIMARY KEY (`ID_ACTU`);


ALTER TABLE `appeler`
  ADD PRIMARY KEY (`ID_APPEL`,`ID_USER`),
  ADD KEY `I_FK_APPELER_APPEL_VIDEO` (`ID_APPEL`),
  ADD KEY `I_FK_APPELER_UTILISATEUR` (`ID_USER`);


ALTER TABLE `appel_video`
  ADD PRIMARY KEY (`ID_APPEL`);


ALTER TABLE `creer`
  ADD PRIMARY KEY (`ID_USER`,`ID_REUNION`),
  ADD KEY `I_FK_CREER_UTILISATEUR` (`ID_USER`),
  ADD KEY `I_FK_CREER_REUNION` (`ID_REUNION`);


ALTER TABLE `envoyer`
  ADD PRIMARY KEY (`ID_USER`,`ID_MESSAGE`),
  ADD KEY `I_FK_ENVOYER_UTILISATEUR` (`ID_USER`),
  ADD KEY `I_FK_ENVOYER_MESSAGE` (`ID_MESSAGE`);


ALTER TABLE `etre_appele`
  ADD PRIMARY KEY (`ID_USER`,`ID_APPEL`),
  ADD KEY `I_FK_ETRE_APPELE_UTILISATEUR` (`ID_USER`),
  ADD KEY `I_FK_ETRE_APPELE_APPEL_VIDEO` (`ID_APPEL`);


ALTER TABLE `message`
  ADD PRIMARY KEY (`ID_MESSAGE`);


ALTER TABLE `recevoir`
  ADD PRIMARY KEY (`ID_MESSAGE`,`ID_USER`),
  ADD KEY `I_FK_RECEVOIR_MESSAGE` (`ID_MESSAGE`),
  ADD KEY `I_FK_RECEVOIR_UTILISATEUR` (`ID_USER`);


ALTER TABLE `reunion`
  ADD PRIMARY KEY (`ID_REUNION`);


ALTER TABLE `utilisateur`
  ADD PRIMARY KEY (`ID_USER`);


ALTER TABLE `actualite`
  MODIFY `ID_ACTU` int(2) NOT NULL AUTO_INCREMENT;


ALTER TABLE `appel_video`
  MODIFY `ID_APPEL` int(2) NOT NULL AUTO_INCREMENT;


ALTER TABLE `message`
  MODIFY `ID_MESSAGE` int(2) NOT NULL AUTO_INCREMENT;


ALTER TABLE `reunion`
  MODIFY `ID_REUNION` int(2) NOT NULL AUTO_INCREMENT;


ALTER TABLE `utilisateur`
  MODIFY `ID_USER` int(2) NOT NULL AUTO_INCREMENT;


ALTER TABLE `appeler`
  ADD CONSTRAINT `FK_APPELER_APPEL_VIDEO` FOREIGN KEY (`ID_APPEL`) REFERENCES `appel_video` (`ID_APPEL`),
  ADD CONSTRAINT `FK_APPELER_UTILISATEUR` FOREIGN KEY (`ID_USER`) REFERENCES `utilisateur` (`ID_USER`);


ALTER TABLE `creer`
  ADD CONSTRAINT `FK_CREER_REUNION` FOREIGN KEY (`ID_REUNION`) REFERENCES `reunion` (`ID_REUNION`),
  ADD CONSTRAINT `FK_CREER_UTILISATEUR` FOREIGN KEY (`ID_USER`) REFERENCES `utilisateur` (`ID_USER`);


ALTER TABLE `envoyer`
  ADD CONSTRAINT `FK_ENVOYER_MESSAGE` FOREIGN KEY (`ID_MESSAGE`) REFERENCES `message` (`ID_MESSAGE`),
  ADD CONSTRAINT `FK_ENVOYER_UTILISATEUR` FOREIGN KEY (`ID_USER`) REFERENCES `utilisateur` (`ID_USER`);


ALTER TABLE `etre_appele`
  ADD CONSTRAINT `FK_ETRE_APPELE_APPEL_VIDEO` FOREIGN KEY (`ID_APPEL`) REFERENCES `appel_video` (`ID_APPEL`),
  ADD CONSTRAINT `FK_ETRE_APPELE_UTILISATEUR` FOREIGN KEY (`ID_USER`) REFERENCES `utilisateur` (`ID_USER`);


ALTER TABLE `recevoir`
  ADD CONSTRAINT `FK_RECEVOIR_MESSAGE` FOREIGN KEY (`ID_MESSAGE`) REFERENCES `message` (`ID_MESSAGE`),
  ADD CONSTRAINT `FK_RECEVOIR_UTILISATEUR` FOREIGN KEY (`ID_USER`) REFERENCES `utilisateur` (`ID_USER`);
COMMIT;